spring:
  ## kafka's properties
  kafka:
    bootstrap-servers: broker:9092

management:
  zipkin:
    tracing:
      endpoint: http:zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@discovery-server:8761/eureka
server:
  port: 8080