spring:
  application:
    name: notification-service

  ## kafka's properties
  kafka:
    bootstrap-servers: localhost:63892
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notificationId
      properties:
        spring:
          json:
            type:
              mapping: event:org.adamasorho.notificationservice.event.OrderPlacedEvent

#management.endpoints.web.exposure.include=*
#management.endpoint.loggers.enabled=true
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        ## dangerous for production usage
        include: "*"
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka
server:
  port: 8084
