version: '3'
services:
  ## Postgres Docker Compose Config
  postgres-order:
    container_name: postgres-order
    image: postgres
    environment:
      POSTGRES_DB: order_service_db
      POSTGRES_USER: psorho
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-order:/data/postgres
    ports:
      - "5431:5431"
    expose:
      - "5431"
    command:
      - -p 5431
    restart: unless-stopped

  postgres-inventory:
    container_name: postgres-inventory
    image: postgres
    environment:
      POSTGRES_DB: inventory_service_db
      POSTGRES_USER: psorho
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-inventory:/data/postgres
      - ./inventory-service/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "5433:5433"
    expose:
      - "5433"
    command:
      - -p 5433
    restart: unless-stopped


  ## MongoDB Docker Compose Config
  mongo-product:
    container_name: mongo-product
    image: mongo:4.4.14-rc0-focal
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-data:/data/db

  ## Keycloak Config with Mysql Database
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:5.7
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: keycloak_db
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    command:
      - "start-dev"
      - "--import-realm"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql
      DB_DATABASE: keycloak
      DB_PASSWORD: password
      DB_USER: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

  ## Zookeeper and Kafka Configuration
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  ## Zipkin Configuration
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  ## Eureka Server Configuration (Discovery Server)
  discovery-server:
    image: adaude/discovery-server:latest
    container_name: discovery-server
    pull_policy: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin

  api-gateway:
    image: adaude/api-gateway:latest
    container_name: api-gateway
    pull_policy: always
    ports:
      - "8181:8080"
    expose:
      - "8181"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
      - eureka.client.service-url.defaultZone=http://eureka:password@discovery-server:8761/eureka
      - spring.security.oauth2.resource-server.jwt.issuer-uri=http://keycloak:8080/realms/spring-boot-microservices-realm
    depends_on:
      - zipkin
      - discovery-server
      - keycloak

  ## Product Service Docker Compose Configuration
  product-service:
    container_name: product-service
    image: adaude/product-service:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
    depends_on:
      - mongo-product
      - discovery-server
      - api-gateway

  ## Order Service Docker Compose Configuration
  order-service:
    container_name: order-service
    image: adaude/order-service:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-order:5431/order_service_db
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
    depends_on:
      - postgres-order
      - broker
      - zipkin
      - discovery-server
      - api-gateway


  ## Inventory Service Docker Compose Configuration
  inventory-service:
    container_name: inventory-service
    image: adaude/inventory-service:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-inventory:5433/inventory_service_db
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
    depends_on:
      - postgres-inventory
      - discovery-server
      - api-gateway
      - zipkin

  ## Notification Service Docker Compose Configuration
  notification-service:
    container_name: notification-service
    image: adaude/notification-service:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
    depends_on:
      - zipkin
      - broker
      - discovery-server
      - api-gateway

  ## Prometheus Configuration
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.9
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - product-service
      - order-service
      - notification-service
      - inventory-service

  ## Grafana Configuration
  grafana:
    image: grafana/grafana-oss:8.5.27
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password