version: '3'
services:
  ## Mysql Docker Compose Config
  mysql-order:
    container_name: mysql-order
    image: mysql:8-debian
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_service_db
      MYSQL_USER: psorho
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-order:/var/lib/mysql
    ports:
      - "3307:3307"
    expose:
      - "3307"
    restart: unless-stopped

  mysql-inventory:
    container_name: mysql-inventory
    image: mysql:8-debian
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_service_db
      MYSQL_USER: psorho
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-inventory:/var/lib/mysql
    ports:
      - "3308:3308"
    expose:
      - "3308"
    restart: unless-stopped


  ## MongoDB Docker Compose Config
  mongo-product:
    container_name: mongo-product
    image: mongo:4.4.14-rc0-focal
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-data:/data/db

  ## Keycloak Config with Mysql Database
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:5.7
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: keycloak_db
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    command:
      - "start-dev"
      - "--import-realm"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_PASSWORD: password
      DB_USER: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

  ## Zookeeper and Kafka Configuration
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  ## Zipkin Configuration
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  ## Eureka Server Configuration (Discovery Server)
  discovery-server:
    image: adaude/discovery-server:latest
    container_name: discovery-server
    pull_policy: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin

  api-gateway:
    image: adaude/api-gateway:latest
    container_name: api-gateway
    pull_policy: always
    ports:
      - "8181:8080"
    expose:
      - "8181"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
    depends_on:
      - zipkin
      - discovery-server
      - keycloak

  ## Product Service Docker Compose Configuration
  product-service:
    container_name: product-service
    image: adaude/product-service:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo-product
      - discovery-server
      - api-gateway

  ## Order Service Docker Compose Configuration
  order-service:
    container_name: order-service
    image: adaude/order-service:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-order:3307/order_service_db
    depends_on:
      - mysql-order
      - broker
      - zipkin
      - discovery-server
      - api-gateway


  ## Inventory Service Docker Compose Configuration
  inventory-service:
    container_name: inventory-service
    image: adaude/inventory-service:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-inventory:3308/inventory_service_db
    depends_on:
      - mysql-inventory
      - discovery-server
      - api-gateway
      - zipkin

  ## Notification Service Docker Compose Configuration
  notification-service:
    container_name: notification-service
    image: adaude/notification-service:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - broker
      - discovery-server
      - api-gateway