spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://keycloak:8080/realms/spring-boot-microservices-realm
  cloud:
    gateway:
      routes:
        ## product service route
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product
        ## order service route
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order
        ## discovery server route
        - id: discovery-server
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        ## discovery server static route
        - id: discovery-server-static
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/**

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@discovery-server:8761/eureka
server:
  port: 8080

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans