spring:
  datasource:
    url: jdbc:postgresql://postgres-order:5431/order_service_db
    username: psorho
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: broker:29092

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@discovery-server:8761/eureka
server:
  port: 8080

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans