spring:
  application:
    name: product-service
  data:
    mongodb:
      host: mongo-product
      port: 27017
      database: product-service-db

  ## for distributed tracing
management:
  tracing:
    sampling:
      probability: 1.0
  ## Prometheus endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka
server:
  port: 8083
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    springframework: ERROR
