spring:
  application:
    name: product-service
  data:
    mongodb:
      host: mongo-product
      port: 27017
      database: product-service-db

  ## for distributed tracing
#  zipkin:
#    base-url: http://localhost:9411
#    sleuth:
#      sampler:
#        probability: 1.0
management:
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka
server:
  port: 8083
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    springframework: ERROR
