spring:
  datasource:
    url: jdbc:postgresql://postgres-inventory:5433/inventory_service_db
    username: psorho
    password: password
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@discovery-server:8761/eureka
server:
  port: 8080

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans