spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:inventory-order}:3308/inventory_service_db
    username: psorho
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@discovery-server:8761/eureka
server:
  port: 8080

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans